# Generated by Django 5.2.5 on 2026-05-28 16:13

import django.db.models.deletion
import mock_interview.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('organization', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Candidate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254)),
                ('created_at', models.BigIntegerField(default=mock_interview.models.current_timestamp)),
                ('updated_at', models.BigIntegerField(default=mock_interview.models.current_timestamp)),
                ('organization', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to='organization.organization')),
            ],
            options={
                'db_table': 'mock_interview_candidate',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='CandidateInterviewer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254)),
                ('created_at', models.BigIntegerField(default=mock_interview.models.current_timestamp)),
                ('updated_at', models.BigIntegerField(default=mock_interview.models.current_timestamp)),
                ('organization', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to='organization.organization')),
            ],
            options={
                'db_table': 'mock_interview_candidate_interviewer',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='InterviewTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('questions', models.JSONField(default=list)),
                ('created_at', models.BigIntegerField(default=mock_interview.models.current_timestamp)),
                ('updated_at', models.BigIntegerField(default=mock_interview.models.current_timestamp)),
                ('organization', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to='organization.organization')),
            ],
            options={
                'db_table': 'mock_interview_template',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='MockSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('candidate_name', models.CharField(max_length=255)),
                ('candidate_email', models.EmailField(blank=True, max_length=254, null=True)),
                ('candidate_interviewer_name', models.CharField(blank=True, max_length=255, null=True)),
                ('candidate_interviewer_email', models.EmailField(blank=True, max_length=254, null=True)),
                ('stack', models.CharField(max_length=100)),
                ('status', models.CharField(choices=[('active', 'Active'), ('completed', 'Completed')], default='active', max_length=20)),
                ('version_label', models.CharField(max_length=100)),
                ('questions', models.JSONField(default=list)),
                ('responses', models.JSONField(default=dict)),
                ('overall_feedback', models.TextField(blank=True, null=True)),
                ('scheduled_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.BigIntegerField(default=mock_interview.models.current_timestamp)),
                ('updated_at', models.BigIntegerField(default=mock_interview.models.current_timestamp)),
                ('candidate', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sessions', to='mock_interview.candidate')),
                ('candidate_interviewer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sessions', to='mock_interview.candidateinterviewer')),
                ('organization', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to='organization.organization')),
                ('registered_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='mock_sessions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Mock Session',
                'verbose_name_plural': 'Mock Sessions',
                'db_table': 'mock_interview_session',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('ideal_answer', models.TextField()),
                ('stack', models.CharField(max_length=100)),
                ('difficulty', models.CharField(choices=[('easy', 'Easy'), ('medium', 'Medium'), ('hard', 'Hard')], default='medium', max_length=20)),
                ('created_at', models.BigIntegerField(default=mock_interview.models.current_timestamp)),
                ('updated_at', models.BigIntegerField(default=mock_interview.models.current_timestamp)),
                ('organization', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to='organization.organization')),
            ],
            options={
                'db_table': 'mock_interview_question',
                'ordering': ['-created_at'],
            },
        ),
    ]
