# Generated by Django 5.2.5 on 2026-06-16 07:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_make_hr_super_admin'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='is_individual',
            field=models.BooleanField(default=True, help_text='True if user is an individual subscriber (isolated), False if part of an organization'),
        ),
    ]
