# Generated by Django 5.2.5 on 2026-05-28 16:13

import premium_ai_interview.models
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AIInterviewSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_id', models.UUIDField(db_index=True, default=uuid.uuid4, unique=True)),
                ('candidate_name', models.CharField(max_length=255)),
                ('candidate_email', models.EmailField(blank=True, default='', max_length=254)),
                ('role', models.CharField(blank=True, default='', max_length=100)),
                ('difficulty', models.CharField(choices=[('easy', 'Easy'), ('medium', 'Medium'), ('hard', 'Hard')], default='medium', max_length=20)),
                ('status', models.CharField(choices=[('active', 'Active'), ('completed', 'Completed')], default='active', max_length=20)),
                ('interview_mode', models.CharField(default='role', max_length=20)),
                ('resume_data', models.JSONField(blank=True, null=True)),
                ('conversation', models.JSONField(default=list)),
                ('scores', models.JSONField(default=list)),
                ('question_number', models.IntegerField(default=0)),
                ('max_questions', models.IntegerField(default=5)),
                ('overall_score', models.FloatField(blank=True, null=True)),
                ('final_report', models.JSONField(blank=True, null=True)),
                ('audio_recordings', models.JSONField(blank=True, default=list)),
                ('interview_video_url', models.URLField(blank=True, default='')),
                ('interview_video_key', models.CharField(blank=True, default='', max_length=1024)),
                ('created_at', models.BigIntegerField(default=premium_ai_interview.models.current_timestamp)),
                ('updated_at', models.BigIntegerField(default=premium_ai_interview.models.current_timestamp)),
            ],
            options={
                'db_table': 'ai_interview_session',
                'ordering': ['-created_at'],
            },
        ),
    ]
