# Generated by Django 5.2.5 on 2026-05-28 16:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AIAssessment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('role_type', models.CharField(choices=[('frontend_developer', 'Frontend Developer'), ('fullstack_developer', 'Full Stack Developer'), ('java_developer', 'Java Developer'), ('python_developer', 'Python Developer'), ('mern_stack_developer', 'MERN Stack Developer'), ('data_scientist', 'Data Scientist'), ('devops_engineer', 'DevOps Engineer'), ('machine_learning_engineer', 'Machine Learning Engineer'), ('data_engineer', 'Data Engineer'), ('ai_engineer', 'AI Engineer'), ('ux_designer', 'UX Designer'), ('salesforce_developer', 'Salesforce Developer'), ('salesforce_admin', 'Salesforce Admin'), ('tableau_developer', 'Tableau Developer'), ('power_bi_developer', 'Power BI Developer'), ('data_analyst', 'Data Analyst'), ('backend_developer', 'Backend Developer'), ('mean_stack_developer', 'MEAN Stack Developer')], default='frontend_developer', max_length=50)),
                ('experience_level', models.CharField(choices=[('fresher', 'Fresher'), ('0-2_years', '0-2 years'), ('2-5_years', '2-5 years'), ('5-8_years', '5-8 years'), ('8+_years', '8+ years')], default='2-5_years', max_length=20)),
                ('start_date', models.DateTimeField()),
                ('end_date', models.DateTimeField()),
                ('instructions', models.TextField(blank=True)),
                ('num_questions', models.PositiveIntegerField(default=5, help_text='Total number of questions in assessment')),
                ('num_hardcoded_questions', models.PositiveIntegerField(default=0, help_text='Number of hardcoded questions to include')),
                ('hardcoded_question_ids', models.JSONField(blank=True, default=list, help_text='List of selected question IDs from question bank')),
                ('num_coding_questions', models.PositiveIntegerField(default=0, help_text='Number of coding questions from question bank')),
                ('coding_time_limit', models.PositiveIntegerField(default=10, help_text='Time limit per coding question in minutes')),
                ('passing_percentage', models.FloatField(default=0, help_text='Minimum percentage (0-100) required to earn a certificate. 0 means no certificate.')),
                ('is_global', models.BooleanField(default=False)),
                ('gemini_api_key', models.CharField(blank=True, help_text='Gemini API key for this assessment', max_length=500)),
                ('enable_voice_recording', models.BooleanField(default=True)),
                ('enable_camera', models.BooleanField(default=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='AIInterviewResponse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_number', models.PositiveIntegerField()),
                ('question_text', models.TextField()),
                ('answer_text', models.TextField(blank=True)),
                ('voice_recording_path', models.CharField(blank=True, max_length=500)),
                ('audio_recording', models.FileField(blank=True, null=True, upload_to='ai_audio/')),
                ('response_time', models.PositiveIntegerField(default=0)),
                ('responded_at', models.DateTimeField(auto_now=True)),
                ('question_type', models.CharField(default='text', max_length=10)),
                ('code_answer', models.TextField(blank=True, default='')),
                ('code_language', models.CharField(blank=True, default='', max_length=20)),
                ('code_execution_results', models.JSONField(blank=True, default=list)),
                ('code_marks_earned', models.FloatField(default=0)),
                ('code_marks_total', models.FloatField(default=0)),
                ('coding_question_id', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'ordering': ['question_number'],
            },
        ),
        migrations.CreateModel(
            name='AIVoiceAnalysis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_number', models.PositiveIntegerField()),
                ('audio_duration_seconds', models.FloatField(default=0)),
                ('transcript_word_count', models.PositiveIntegerField(default=0)),
                ('speech_rate_wpm', models.FloatField(default=0)),
                ('pause_count', models.PositiveIntegerField(default=0)),
                ('long_pause_count', models.PositiveIntegerField(default=0)),
                ('longest_pause_seconds', models.FloatField(default=0)),
                ('pause_timeline', models.JSONField(blank=True, default=list)),
                ('speech_rate_timeline', models.JSONField(blank=True, default=list)),
                ('filler_word_count', models.PositiveIntegerField(default=0)),
                ('sentence_complexity_delta', models.FloatField(default=0)),
                ('answer_structure_score', models.FloatField(default=0)),
                ('mid_answer_shift_score', models.FloatField(default=0)),
                ('llm_consistency_score', models.FloatField(default=0)),
                ('overall_risk_score', models.FloatField(default=0)),
                ('risk_level', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High')], default='low', max_length=10)),
                ('signals', models.JSONField(blank=True, default=list)),
                ('llm_review', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['question_number'],
            },
        ),
        migrations.CreateModel(
            name='CandidateAIAssessment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('assigned_date', models.DateTimeField(auto_now_add=True)),
                ('resume_text', models.TextField(help_text="Candidate's tech stack")),
                ('start_time', models.DateTimeField(blank=True, null=True)),
                ('end_time', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('assigned', 'Assigned'), ('in_progress', 'In Progress'), ('completed', 'Completed')], default='assigned', max_length=20)),
                ('generated_questions', models.JSONField(blank=True, default=list)),
                ('questions_generation_status', models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('completed', 'Completed'), ('failed', 'Failed')], default='pending', help_text='Status of question generation', max_length=20)),
                ('ai_feedback', models.TextField(blank=True)),
                ('question_wise_verification', models.JSONField(blank=True, default=list)),
                ('technical_score', models.FloatField(default=0)),
                ('communication_score', models.FloatField(default=0)),
                ('problem_solving_score', models.FloatField(default=0)),
                ('overall_score', models.FloatField(default=0)),
                ('technical_feedback', models.TextField(blank=True, default='')),
                ('communication_feedback', models.TextField(blank=True, default='')),
                ('problem_solving_feedback', models.TextField(blank=True, default='')),
                ('strengths_feedback', models.TextField(blank=True, default='')),
                ('improvement_feedback', models.TextField(blank=True, default='')),
                ('overall_feedback', models.TextField(blank=True, default='')),
                ('introduction_video_url', models.URLField(blank=True, help_text='S3 URL for introduction video', max_length=500, null=True)),
                ('introduction_video', models.FileField(blank=True, null=True, upload_to='ai_introductions/')),
                ('assessment_video_url', models.URLField(blank=True, help_text='S3 URL for complete assessment recording', max_length=500, null=True)),
                ('interview_video', models.FileField(blank=True, null=True, upload_to='ai_videos/')),
                ('interview_video_url', models.URLField(blank=True, help_text='S3 URL for interview recording', max_length=500, null=True)),
                ('screenshots', models.JSONField(blank=True, default=list)),
                ('periodic_screenshots', models.JSONField(blank=True, default=list)),
                ('gesture_analysis', models.JSONField(blank=True, default=dict)),
                ('communication_metrics', models.JSONField(blank=True, default=dict)),
                ('cheating_alerts', models.JSONField(blank=True, default=list)),
                ('voice_flow_analysis', models.JSONField(blank=True, default=dict)),
                ('voice_flow_risk_score', models.FloatField(default=0)),
                ('voice_flow_risk_level', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High')], default='low', max_length=10)),
                ('multiple_faces_count', models.IntegerField(default=0)),
                ('gaze_violation_count', models.IntegerField(default=0)),
                ('no_face_detection_count', models.IntegerField(default=0)),
                ('total_proctor_warnings', models.IntegerField(default=0)),
                ('admin_feedback', models.TextField(blank=True, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('profile_key', models.CharField(choices=[('frontend_developer', 'Frontend Developer'), ('fullstack_developer', 'Full Stack Developer'), ('java_developer', 'Java Developer'), ('python_developer', 'Python Developer'), ('mern_stack_developer', 'MERN Stack Developer'), ('data_scientist', 'Data Scientist'), ('devops_engineer', 'DevOps Engineer'), ('machine_learning_engineer', 'Machine Learning Engineer'), ('data_engineer', 'Data Engineer'), ('ai_engineer', 'AI Engineer'), ('ux_designer', 'UX Designer'), ('salesforce_developer', 'Salesforce Developer'), ('salesforce_admin', 'Salesforce Admin'), ('tableau_developer', 'Tableau Developer'), ('power_bi_developer', 'Power BI Developer'), ('data_analyst', 'Data Analyst'), ('backend_developer', 'Backend Developer'), ('mean_stack_developer', 'MEAN Stack Developer')], max_length=50, unique=True)),
                ('description', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.TextField(help_text='The interview question')),
                ('complexity_level', models.CharField(choices=[('fresher', 'Fresher'), ('0-2_years', '0-2 years'), ('2-5_years', '2-5 years'), ('5-8_years', '5-8 years'), ('8+_years', '8+ years')], max_length=20)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='QuestionProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['profile', 'question'],
            },
        ),
    ]
