# Generated by Django 5.2.5 on 2026-05-28 16:13

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('AI_assessment', '0001_initial'),
        ('organization', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='aiassessment',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='aiassessment',
            name='organization',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to='organization.organization'),
        ),
        migrations.AddField(
            model_name='aiassessment',
            name='visible_to_organizations',
            field=models.ManyToManyField(blank=True, related_name='shared_ai_assessments', to='organization.organization'),
        ),
        migrations.AddField(
            model_name='aiinterviewresponse',
            name='organization',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to='organization.organization'),
        ),
        migrations.AddField(
            model_name='aivoiceanalysis',
            name='organization',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to='organization.organization'),
        ),
        migrations.AddField(
            model_name='aivoiceanalysis',
            name='response',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='voice_analysis', to='AI_assessment.aiinterviewresponse'),
        ),
        migrations.AddField(
            model_name='candidateaiassessment',
            name='ai_assessment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='AI_assessment.aiassessment'),
        ),
        migrations.AddField(
            model_name='candidateaiassessment',
            name='assigned_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assigned_ai_assessments', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='candidateaiassessment',
            name='candidate',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='candidateaiassessment',
            name='organization',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to='organization.organization'),
        ),
        migrations.AddField(
            model_name='aivoiceanalysis',
            name='candidate_assessment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='voice_analyses', to='AI_assessment.candidateaiassessment'),
        ),
        migrations.AddField(
            model_name='aiinterviewresponse',
            name='candidate_assessment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='AI_assessment.candidateaiassessment'),
        ),
        migrations.AddField(
            model_name='profile',
            name='organization',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to='organization.organization'),
        ),
        migrations.AddField(
            model_name='question',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_questions', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='question',
            name='organization',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to='organization.organization'),
        ),
        migrations.AddField(
            model_name='question',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_questions', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='questionprofile',
            name='organization',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to='organization.organization'),
        ),
        migrations.AddField(
            model_name='questionprofile',
            name='profile',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='question_links', to='AI_assessment.profile'),
        ),
        migrations.AddField(
            model_name='questionprofile',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='profile_links', to='AI_assessment.question'),
        ),
        migrations.AddIndex(
            model_name='aivoiceanalysis',
            index=models.Index(fields=['candidate_assessment', 'risk_level'], name='AI_assessme_candida_2c55d3_idx'),
        ),
        migrations.AddIndex(
            model_name='aivoiceanalysis',
            index=models.Index(fields=['overall_risk_score'], name='AI_assessme_overall_56a3d1_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='aivoiceanalysis',
            unique_together={('candidate_assessment', 'question_number')},
        ),
        migrations.AlterUniqueTogether(
            name='aiinterviewresponse',
            unique_together={('candidate_assessment', 'question_number')},
        ),
        migrations.AddIndex(
            model_name='question',
            index=models.Index(fields=['complexity_level', 'is_active'], name='AI_assessme_complex_7ea6db_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='questionprofile',
            unique_together={('question', 'profile')},
        ),
    ]
