# Generated by Django 5.2.5 on 2026-06-17 07:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AI_assessment', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='aiassessment',
            name='tech_stack',
            field=models.JSONField(blank=True, default=list, help_text='Skills/technologies this AI assessment targets.'),
        ),
    ]
