# Generated by Django 5.2.5 on 2026-06-04 13:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='organization',
            name='candidate_limit',
            field=models.PositiveIntegerField(blank=True, help_text='Max number of candidates this organization can invite. Null = unlimited.', null=True),
        ),
    ]
