export const PROFILE_OPTIONS: string[] = [
  "Python Developer",
  "Python & Django Developer",
  "Python & SQL Developer",
  "Java Developer",
  "Java & Node Developer",
  "Java & React Developer",
  "Java Full Stack Developer",
  "React Developer",
  "React & Node.JS Developer",
  "Mern Stack Developer",
  "Mean Stack Developer",
  "Node.JS Developer",
  "Angular Developer",
  "PHP Developer",
  "Associate Software Developer",
  "Frontend Developer",
  "Backend Developer",
  "Data Engineer",
  "Data Analyst",
  "Data Scientist (AI & ML)",
  "BDE",
  "Full Stack Developer",
  "QA/Test Engineer",
  "Software Engineer",
  "Web Developer",
  "UI/UX Developer",
  "SQL Developer",
  "System Engineer",
  "Technical Support",
  "DevOps Engineer",
  "Cloud Engineer",
  ".Net Developer",
];
